---
 - name: Laucnh AWS EC2 instance
   hosts: localhost
   vars:
     - aws_region: ap-south-1
     - ami_id: ami-0e306788ff2473ccb 
     - key_name: aws-ansible
     - sg_name: aws-ansible-sg
     - vpc_id: 
     - security_group_ports: 
       - 80
       - 22
     - email_id: 
     - email_pass: 
   tasks:
     - name: generate key pairs
       ec2_key: 
         name: "{{ key_name }}"
         region: "{{ aws_region }}"
       register: aws_ec2_key_result

     - name: store private key pair
       copy:
         content: "{{ aws_ec2_key_result.key.private_key }}"
         dest: ./{{ key_name }}.pem
         mode: 0400

     - name: create aws security group
       ec2_group:
         name: "{{ sg_name  }}"
         description: aws security group
         vpc_id: "{{ vpc_id }}"
         rules:
         - proto: tcp
           ports: "{{ security_group_ports }}"
           cidr_ip: 0.0.0.0/0
           cidr_ipv6: ::/0
           rule_desc: allow all on port 80 and 22
       when: aws_ec2_key_result.changed
 
